//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormsLinq
{
    using System;
    using System.Collections.Generic;
    
    public partial class automovil
    {
        public int id { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public Nullable<int> anno { get; set; }
        public string color { get; set; }
        public Nullable<int> CIPropietario { get; set; }
    }
}
